# config/config.yaml

csv_path: csv/players3.csv
output_folder: "C:\\Users\\itato\\Dropbox\\ChatGptPromptParser"
status_folder: "C:\\Users\\itato\\Dropbox\\ChatGptPromptParser"
initial_wait: 1
typing_interval: 0.05
press_enter_after: false
delay_between: 2
test_macro_only: false

macros:
  PromptMaster:
    actions:
      - press_key: "win+3"
      - wait: 1
      - press_key: "ctrl+1"
      - wait: 1
      - mouse_click:
          x: 41
          y: 365              # Click  new chat
      - wait: 4
      - mouse_click:
          x: 1332
          y: 817              # Click  inside the chat
      - wait: 7
      - pyclip: "{{prompt}}"
      - wait: 0.5
      - press_key: "ctrl+v"
      - wait: 1
      - press_key: "enter"
      - wait: [10, 20]    # ← random between 4–6 min (240–360 s)
      - press_key: "F12"
      - wait: 2
      - press_key: "ctrl+f"
      - wait: 2
      - write: "@thread-xl/thread:pt-header-height mt-1.5 flex flex-col text-sm pb-25"
      - wait: 8
      - press_key: "tab"
      - wait: 1
      - press_key: "tab"
      - wait: 1
      - press_key: "tab"
      - wait: 1
      - press_key: "enter"
      - wait: 1
      - press_key: "shift+F10"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "right"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "enter"
      - wait: 4
      - press_key: "F12"
      - wait: [10, 20]      # ← random between 0–2 min (0–120 s) delete
      - mouse_click:
          x: 2289
          y: 284              # Click necessary position
      - wait: 1
      - mouse_click:
          x: 2118
          y: 481              # Click necessary position
      - wait: 1
      - press_key: "enter"
      - wait: 1
      - press_key: "win+3"