# config/config.yaml

csv_path: csv/players3.csv
output_folder: "C:\\Users\\itato\\Dropbox\\ChatGptPromptParser"
status_folder: "C:\\Users\\itato\\Dropbox\\ChatGptPromptParser"
initial_wait: 1
typing_interval: 0.05
press_enter_after: false
delay_between: 2
test_macro_only: false

macros:
  PromptMaster:
    actions:
      - press_key: "win+3"
      - wait: 1
      - press_key: "ctrl+1"
      - wait: 1
      - mouse_click:
          x: 33
          y: 295              # Click  new chat
      - wait: 4
      - mouse_click:
          x: 1372
          y: 761              # Click  inside the chat
      - wait: 7
      - pyclip: "{{prompt}}"
      - wait: 0.5
      - press_key: "ctrl+v"
      - wait: 1
      - press_key: "enter"
      - wait: 180
      - press_key: "F12"
      - wait: 2
      - press_key: "ctrl+f"
      - wait: 2
      - write: "@thread-xl/thread:pt-header-height mt-1.5 flex flex-col text-sm pb-25"
      - wait: 8
      - press_key: "tab"
      - wait: 1
      - press_key: "tab"
      - wait: 1
      - press_key: "tab"
      - wait: 1
      - press_key: "enter"
      - wait: 1
      - press_key: "shift+F10"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "right"
      - wait: 1
      - press_key: "down"
      - wait: 1
      - press_key: "enter"
      - wait: 4
      - press_key: "F12"
      - wait: 1             #deleting thread
      - mouse_click:
          x: 1864
          y: 137              # Click necessary position
      - wait: 1
      - mouse_click:
          x: 1784
          y: 242              # Click necessary position
      - wait: 1
      - press_key: "enter"
      - wait: 1
      - press_key: "win+3"
shift:
  start_hour: 0               # start “now” whenever you run
  shift_length_hours: 0.1     # ~6 minutes total shift
  lunch:
    duration_minutes: 1       # 1-minute “lunch”
    earliest_start_hour: 0    # can lunch right away
    latest_start_hour: 0
  breaks:
    count: 2
    duration_minutes: 0.5     # 30-second breaks
    earliest_start_hour: 0
    latest_end_hour: 1        # must finish breaks within the first hour
  randomize: false            # fixed times so it’s repeatable