# config/config.yaml

csv_path: csv/players2.csv
initial_wait: 1
typing_interval: 0.05
press_enter_after: true   # or false, if you don’t want an automatic ↵
delay_between: 2
test_macro_only: true

macros:
  PromptMaster:
    actions:
      - press_key: "win+5"
      - wait: 1
      - press_key: "ctrl+1"
      - wait: 1
      - press_key: "ctrl+shift+O"
      - wait: 7
      - pyclip: "{{prompt}}"
      - wait: 0.5
      - press_key: "ctrl+v"
      - wait: 1
      - press_key: "enter"
      - wait: 120